name : NextJS Continuous Integration

on:
    push:
        branches:
        - master
    pull_request:
        branches:
        - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Install dependencies
          run: npm ci
        - name: Lint
          run: npm run lint
        - name: dev
          run: npm run dev
        - name: Start
          run: npm run start
        - name: Build
          run: npm run build